#cloud-config

package_update: true
package_upgrade: true

write_files:
  - path: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb http://apt.kubernetes.io/ kubernetes-xenial main
  - path: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

runcmd:
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

  - apt update -y && apt install -y kubelet kubeadm kubectl docker.io && apt-mark hold kubelet kubeadm kubectl

  - modprobe overlay && modprobe br_netfilter && sysctl --system

  - mkdir -p /etc/containerd

  - containerd config default | tee /etc/containerd/config.toml 
  - sed -i "s/SystemdCgroup = false/SystemdCgroup = true/g" /etc/containerd/config.toml

  - systemctl restart docker && systemctl enable docker

  - systemctl enable --now kubelet

  - kubeadm config images pull 
