apiVersion: v1
kind: Secret
metadata:
  name: certificate-secret
  namespace: example-ns
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    <PEM encoded leaf/server certificate>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    <PEM encoded intermediate CA certificate 1>
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    <PEM encoded intermediate CA certificate 2>
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    <PEM Privatekey as base64 string>
    -----END PRIVATE KEY-----