apiVersion: v1
kind: Namespace
metadata:
  name: "nginx-example"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-example
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      namespace: nginx-example
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-example
  name: nginx-lb
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
