apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  annotations:
    #Enter the external IP here
    metallb.universe.tf/address-pool: metallb-system
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer